package com.example.mediaparser;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.example.mediaparser.cloud.OpenListClient;
import com.example.mediaparser.cloud.OpenListSettings;
import com.example.mediaparser.core.ShareTextAnalyzer;
import com.example.mediaparser.model.MediaItem;
import com.example.mediaparser.util.FileSaver;

import java.net.URI;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Cloud-drive direct-link page. It integrates a user-owned OpenList server and never bypasses provider auth. */
public final class CloudDriveActivity extends Activity {
    static final String ACTION_OPEN_CLOUD_MEDIA="com.example.mediaparser.OPEN_CLOUD_MEDIA";
    private static final int BLUE=Color.rgb(39,100,231),TEXT=Color.rgb(23,27,35),MUTED=Color.rgb(103,112,126),BORDER=Color.rgb(224,228,236),PANEL=Color.rgb(247,249,252);
    private final ExecutorService executor=Executors.newFixedThreadPool(2);
    private EditText shareInput,pathInput,filePassword,serverInput,tokenInput,userInput,passwordInput;
    private TextView status,settingsStatus;
    private ProgressBar progress;
    private LinearLayout resultBox,settingsBody;
    private boolean busy;
    private OpenListClient.FileResult current;

    @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(buildUi());String initial=getIntent().getStringExtra(Intent.EXTRA_TEXT);if(initial!=null&&!initial.isBlank()){shareInput.setText(initial);analyze();}}
    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
    private View buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(18),dp(16),dp(30));root.setOnApplyWindowInsetsListener((v,i)->{if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets x=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(16),dp(18)+x.top,dp(16),dp(30)+x.bottom);}return i;});scroll.addView(root);root.addView(navigation());root.addView(text("网盘媒体直链",27,TEXT,true));TextView intro=text("接入你自己的 OpenList / AList，获取已挂载网盘文件的临时源站直链；也能识别 115、阿里云盘、夸克、百度等分享文案和提取码。",14,MUTED,false);intro.setPadding(0,dp(6),0,dp(12));root.addView(intro);
        shareInput=input("粘贴网盘分享文案、OpenList 网页地址、/d/ 直链或文件路径",false);shareInput.setMinLines(4);root.addView(shareInput,new LinearLayout.LayoutParams(-1,-2));LinearLayout pasteRow=new LinearLayout(this);pasteRow.setGravity(Gravity.END);Button paste=secondary("粘贴");paste.setOnClickListener(v->paste());Button clear=secondary("清空");clear.setOnClickListener(v->{shareInput.setText("");pathInput.setText("");resultBox.removeAllViews();resultBox.setVisibility(View.GONE);status.setText("");});pasteRow.addView(paste);LinearLayout.LayoutParams cr=new LinearLayout.LayoutParams(-2,-2);cr.setMarginStart(dp(8));pasteRow.addView(clear,cr);root.addView(pasteRow);
        pathInput=input("OpenList 文件路径，例如 /115/视频/课程.mp4",true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.topMargin=dp(8);root.addView(pathInput,pp);filePassword=input("可选：OpenList 路径访问密码",true);filePassword.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(48));fp.topMargin=dp(8);root.addView(filePassword,fp);
        Button parse=primary("识别分享 / 获取直链");parse.setOnClickListener(v->analyze());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(50));bp.topMargin=dp(10);root.addView(parse,bp);LinearLayout sr=new LinearLayout(this);sr.setGravity(Gravity.CENTER_VERTICAL);progress=new ProgressBar(this);progress.setVisibility(View.GONE);sr.addView(progress,new LinearLayout.LayoutParams(dp(24),dp(24)));status=text("",13,MUTED,false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,-2,1);sp.setMarginStart(dp(8));sr.addView(status,sp);root.addView(sr);
        resultBox=new LinearLayout(this);resultBox.setOrientation(LinearLayout.VERTICAL);resultBox.setVisibility(View.GONE);root.addView(resultBox);
        root.addView(settingsCard());TextView legal=text("只处理你有权访问的文件。MediaParser 不破解网盘登录、会员、分享密码或防盗链；分享页不是媒体直链时会明确提示。OpenList 凭证只在 Android Keystore 中加密保存。",12,MUTED,false);legal.setPadding(0,dp(16),0,0);root.addView(legal);return scroll;}

    private View navigation(){LinearLayout n=new LinearLayout(this);String[] labels={"直连解析","网盘直链","本地处理","API 设置"};Button[] b={nav(labels[0],false),nav(labels[1],true),nav(labels[2],false),nav(labels[3],false)};for(int i=0;i<b.length;i++){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(44),1);if(i>0)p.setMarginStart(dp(4));n.addView(b[i],p);}b[0].setOnClickListener(v->startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)));b[2].setOnClickListener(v->startActivity(new Intent(this,LocalMediaActivity.class)));b[3].setOnClickListener(v->startActivity(new Intent(this,ApiSettingsActivity.class)));LinearLayout.LayoutParams o=new LinearLayout.LayoutParams(-1,-2);o.bottomMargin=dp(16);n.setLayoutParams(o);return n;}
    private View settingsCard(){LinearLayout card=panel();LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(16);card.setLayoutParams(cp);Button toggle=secondary("OpenList 服务器设置（点击展开）");card.addView(toggle,new LinearLayout.LayoutParams(-1,dp(46)));settingsStatus=text("",12,MUTED,false);settingsStatus.setPadding(0,dp(6),0,0);card.addView(settingsStatus);settingsBody=new LinearLayout(this);settingsBody.setOrientation(LinearLayout.VERTICAL);settingsBody.setVisibility(View.GONE);card.addView(settingsBody);OpenListSettings.Config old=OpenListSettings.load(this);serverInput=input("https://你的 OpenList 域名",true);serverInput.setText(old.server);tokenInput=input(old.token.isBlank()?"可选：OpenList Token":"Token 已保存，留空保持不变",true);tokenInput.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);userInput=input("可选：OpenList 用户名",true);userInput.setText(old.username);passwordInput=input(old.password.isBlank()?"可选：OpenList 密码":"密码已保存，留空保持不变",true);passwordInput.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);for(EditText e:new EditText[]{serverInput,tokenInput,userInput,passwordInput}){LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(47));ep.topMargin=dp(8);settingsBody.addView(e,ep);}LinearLayout row=new LinearLayout(this);Button test=primary("加密保存并测试"),wipe=secondary("清除");row.addView(test,new LinearLayout.LayoutParams(0,dp(46),2));LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(0,dp(46),1);wp.setMarginStart(dp(8));row.addView(wipe,wp);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.topMargin=dp(8);settingsBody.addView(row,rp);toggle.setOnClickListener(v->{boolean show=settingsBody.getVisibility()!=View.VISIBLE;settingsBody.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText(show?"收起 OpenList 设置":"OpenList 服务器设置（点击展开）");});test.setOnClickListener(v->saveAndTest(test));wipe.setOnClickListener(v->{OpenListSettings.clear(this);serverInput.setText("");tokenInput.setText("");userInput.setText("");passwordInput.setText("");updateSettings();});updateSettings();return card;}
    private void saveAndTest(Button button){if(busy)return;OpenListSettings.Config old=OpenListSettings.load(this);String token=tokenInput.getText().toString().trim(),user=userInput.getText().toString().trim(),pass=passwordInput.getText().toString();if(token.isBlank()&&user.equals(old.username))token=old.token;if(pass.isBlank()&&user.equals(old.username))pass=old.password;if(!tokenInput.getText().toString().isBlank()){user="";pass="";}else if(!userInput.getText().toString().isBlank()){token="";}OpenListSettings.Config c=new OpenListSettings.Config(serverInput.getText().toString(),token,user,pass);try{OpenListSettings.save(this,c);tokenInput.setText("");passwordInput.setText("");}catch(Exception e){settingsStatus.setText("保存失败："+msg(e));return;}busy=true;button.setEnabled(false);button.setText("测试中…");executor.execute(()->{try{String m=new OpenListClient(c).test();runOnUiThread(()->{busy=false;button.setEnabled(true);button.setText("加密保存并测试");settingsStatus.setText(m+" · "+c.masked());toast(m);});}catch(Exception e){runOnUiThread(()->{busy=false;button.setEnabled(true);button.setText("加密保存并测试");settingsStatus.setText("测试失败："+msg(e));});}});}
    private void updateSettings(){OpenListSettings.Config c=OpenListSettings.load(this);settingsStatus.setText(c.configured()?"已配置 "+safeHost(c.server)+" · "+c.masked():"尚未配置；需要你自己的 HTTPS OpenList / AList 服务");}

    private void analyze(){if(busy)return;String raw=shareInput.getText().toString().trim(),explicit=pathInput.getText().toString().trim();if(raw.isBlank()&&explicit.isBlank()){toast("先粘贴分享文案或填写文件路径");return;}ShareTextAnalyzer.Analysis a=ShareTextAnalyzer.analyze(raw.isBlank()?explicit:raw);resultBox.removeAllViews();resultBox.setVisibility(View.VISIBLE);current=null;if(a.providerShare()){showProvider(a);return;}OpenListSettings.Config c=OpenListSettings.load(this);String path=explicit;if(path.isBlank()&&c.configured()&&a.url.startsWith(c.server))path=a.path;if(path.isBlank()&&raw.startsWith("/"))path=raw;if(!a.url.isBlank()&&isDirectMedia(a.url)&&(a.url.contains("/d/")||!c.configured())){showDirect(a.url,lastName(a.url));return;}if(!c.configured()){status.setText("已识别 OpenList 地址/路径，但还没有配置服务器");settingsBody.setVisibility(View.VISIBLE);return;}if(path.isBlank()){status.setText("已识别地址，但无法确定服务器内文件路径；请在“OpenList 文件路径”填写 /网盘/目录/文件名");return;}busy=true;progress.setVisibility(View.VISIBLE);status.setText("正在向你配置的 OpenList 查询文件…");String finalPath=path;executor.execute(()->{try{OpenListClient.FileResult r=new OpenListClient(c).get(finalPath,filePassword.getText().toString());runOnUiThread(()->{busy=false;progress.setVisibility(View.GONE);status.setText("获取成功 · 临时源站直链可能会过期");showOpenList(r);});}catch(Exception e){runOnUiThread(()->{busy=false;progress.setVisibility(View.GONE);status.setText(msg(e));});}});}
    private void showProvider(ShareTextAnalyzer.Analysis a){status.setText("已识别 "+a.label+(a.code.isBlank()?"":" · 提取码 "+a.code));LinearLayout p=panel();p.addView(text(a.label+" 分享页",17,TEXT,true));TextView u=text(a.url,12,MUTED,false);u.setTextIsSelectable(true);u.setPadding(0,dp(6),0,dp(6));p.addView(u);p.addView(text("分享页不是媒体文件地址。请先在网盘官方页面保存/授权，再通过你自己的 OpenList 挂载路径获取直链；App 不会绕过登录、会员或访问权限。",13,MUTED,false));LinearLayout row=new LinearLayout(this);Button open=secondary("打开官方分享页"),copy=secondary("复制链接+提取码");open.setOnClickListener(v->open(a.url));copy.setOnClickListener(v->copy(a.url+(a.code.isBlank()?"":" 提取码："+a.code),"已复制分享信息"));row.addView(open,new LinearLayout.LayoutParams(0,dp(45),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(45),1);cp.setMarginStart(dp(8));row.addView(copy,cp);p.addView(row);resultBox.addView(p);}
    private void showOpenList(OpenListClient.FileResult r){current=r;resultBox.removeAllViews();LinearLayout p=panel();p.addView(text(r.name,17,TEXT,true));p.addView(text("OpenList 路径："+r.path+(r.size>=0?"\n大小："+formatSize(r.size):""),12,MUTED,false));TextView raw=text(r.rawUrl,12,MUTED,false);raw.setTextIsSelectable(true);raw.setPadding(0,dp(8),0,dp(8));p.addView(raw);LinearLayout row=new LinearLayout(this);Button c1=secondary("复制临时源站直链"),c2=secondary("复制 /d/ 地址");c1.setOnClickListener(v->copy(r.rawUrl,"已复制临时源站直链"));c2.setOnClickListener(v->copy(r.stableUrl,"已复制 OpenList /d/ 地址"));row.addView(c1,new LinearLayout.LayoutParams(0,dp(45),1));LinearLayout.LayoutParams c2p=new LinearLayout.LayoutParams(0,dp(45),1);c2p.setMarginStart(dp(8));row.addView(c2,c2p);p.addView(row);Button use=primary("交给直连页：保存 / 提音频 / 生成字幕");LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-1,dp(48));up.topMargin=dp(8);p.addView(use,up);use.setOnClickListener(v->sendToMain(r));Button save=secondary("直接保存到 Download");LinearLayout.LayoutParams sv=new LinearLayout.LayoutParams(-1,dp(46));sv.topMargin=dp(8);p.addView(save,sv);save.setOnClickListener(v->save(r,save));p.addView(text("“临时源站直链”通常可直接下载但可能过期；“/d/ 地址”较稳定，但私有站点仍可能要求 OpenList 登录或签名。115 等源站可能绑定 User-Agent，App 会沿用 OpenList 返回的安全请求头。",11,MUTED,false));resultBox.addView(p);}
    private void showDirect(String url,String name){status.setText("已识别可用的 HTTPS 媒体直链");OpenListClient.FileResult r=new OpenListClient.FileResult(name,"",url,url,-1,java.util.Map.of());showOpenList(r);}
    private void save(OpenListClient.FileResult r,Button b){if(busy)return;busy=true;b.setEnabled(false);b.setText("保存中…");MediaItem item=item(r);executor.execute(()->{try{FileSaver.save(this,item,r.name);runOnUiThread(()->{busy=false;b.setEnabled(true);b.setText("已保存到 Download");toast("保存完成");});}catch(Exception e){runOnUiThread(()->{busy=false;b.setEnabled(true);b.setText("重试保存");toast(msg(e));});}});}
    private MediaItem item(OpenListClient.FileResult r){String l=r.name.toLowerCase();MediaItem.Type t=l.matches(".*\\.(jpg|jpeg|png|webp)$")?MediaItem.Type.IMAGE:l.matches(".*\\.(mp3|m4a|aac|wav|flac)$")?MediaItem.Type.AUDIO:MediaItem.Type.VIDEO;return new MediaItem(t,r.name,r.rawUrl,r.headers);}
    private void sendToMain(OpenListClient.FileResult r){Intent i=new Intent(this,MainActivity.class);i.setAction(ACTION_OPEN_CLOUD_MEDIA);i.putExtra("url",r.rawUrl);i.putExtra("name",r.name);i.putExtra("user_agent",r.headers.getOrDefault("User-Agent",r.headers.getOrDefault("user-agent","")));i.putExtra("referer",r.headers.getOrDefault("Referer",r.headers.getOrDefault("referer","")));i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);}
    private void paste(){ClipboardManager cm=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);if(cm==null||!cm.hasPrimaryClip()){toast("剪贴板没有文本");return;}CharSequence s=cm.getPrimaryClip().getItemAt(0).coerceToText(this);shareInput.setText(s==null?"":s);}
    private void copy(String s,String message){ClipboardManager cm=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);if(cm!=null)cm.setPrimaryClip(ClipData.newPlainText("link",s));toast(message);}private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){toast("无法打开浏览器");}}
    private static boolean isDirectMedia(String u){try{return URI.create(u).getPath().toLowerCase().matches(".*\\.(mp4|m4v|mov|mkv|webm|mp3|m4a|aac|wav|flac|jpg|jpeg|png|webp)$");}catch(Exception e){return false;}}private static String lastName(String u){try{String p=URI.create(u).getPath();return p.substring(p.lastIndexOf('/')+1);}catch(Exception e){return"media";}}private static String safeHost(String u){try{return URI.create(u).getHost();}catch(Exception e){return u;}}private static String formatSize(long x){if(x<1024)return x+" B";if(x<1024*1024)return String.format(java.util.Locale.ROOT,"%.1f KB",x/1024d);if(x<1024L*1024*1024)return String.format(java.util.Locale.ROOT,"%.1f MB",x/1024d/1024);return String.format(java.util.Locale.ROOT,"%.2f GB",x/1024d/1024/1024);}private static String msg(Throwable e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(14),dp(14),dp(14),dp(14));p.setBackground(round(PANEL,dp(14),BORDER,1));return p;}private EditText input(String h,boolean one){EditText e=new EditText(this);e.setHint(h);e.setTextSize(14);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(145,151,162));e.setSingleLine(one);e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setBackground(round(Color.WHITE,dp(12),BORDER,1));return e;}private TextView text(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setLineSpacing(0,1.08f);return v;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(BLUE,dp(11),BLUE,0));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(13);b.setAllCaps(false);b.setBackground(round(Color.WHITE,dp(10),BORDER,1));return b;}private Button nav(String s,boolean active){Button b=active?primary(s):secondary(s);b.setTextSize(12);b.setPadding(0,0,0,0);return b;}private GradientDrawable round(int f,int r,int sc,int sw){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(r);if(sw>0)d.setStroke(dp(sw),sc);return d;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
